language: python

python:
  - "3.4"

#before_install:
#    - sudo apt-get update
#    - sudo apt-get install python3
#    - sudo apt-get install python3-dev
#    - sudo apt-get install python3-yaml

install:
    - pip install .
    - pip install --user -r python/requirements.txt

cache:
  apt: true

script:
    - bash ./travis_bash.sh
    - bash ./travis_deleteInstuckProgress.sh
